apiVersion: v2
name: vault-key
description: Vault SDK - Tokenization and Encryption Service
type: application
version: 1.0.5
appVersion: "1.0.5"
keywords:
  - vault
  - tokenization
  - encryption
  - security
  - pii
maintainers:
  - name: Vault Team
    email: vault@example.com


