{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vault-sdk.fullname" . }}-secret
  labels:
    {{- include "vault-sdk.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.config.databaseUrl | quote }}
  redis-url: {{ .Values.config.redisUrl | quote }}
  aws-kms-key-id: {{ .Values.secrets.awsKmsKeyId | quote }}
  aws-access-key-id: {{ .Values.secrets.awsAccessKeyId | quote }}
  aws-secret-access-key: {{ .Values.secrets.awsSecretAccessKey | quote }}
  kms-api-key: {{ .Values.secrets.kmsApiKey | quote }}
  kms-client-id: {{ .Values.secrets.kmsClientId | quote }}
  token-key: {{ .Values.secrets.tokenKey | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: securelytix-pull-secret
  labels:
    {{- include "vault-sdk.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"docker.io\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.secrets.dockerhubUsername .Values.secrets.dockerhubToken (printf "%s:%s" .Values.secrets.dockerhubUsername .Values.secrets.dockerhubToken | b64enc) | b64enc }}
